Cleanup: - allgohans.safe is a superset of allgohans, so rename it. - reportload.sh is obsolete as reportload is called via inetd. - checkmachines' loop is now part of pollmachine. - retcode belongs to qmanager. - dopackages2 is abandoned. - move pnohang and ptimeout sources to a separate directory. - make prunebad and zexpire executable.

diff --git a/scripts/allgohans b/scripts/allgohans
--- a/scripts/allgohans
+++ b/scripts/allgohans
@@ -21,7 +21,11 @@ doarch() {
 	if [ ${quiet} -eq 0 ]; then
 	    echo "[$i]"
 	fi
-	su ports-${arch} -c "ssh ${client_user}@$i ${sudo_cmd} $@"
+	lockf -t 60 ${pb}/${arch}/lockfiles/lock.$i su ports-${arch} -c "ssh ${client_user}@$i ${sudo_cmd} $@"
+	result=$?
+	if [ $result -ne 0 ]; then
+	    echo "could not execute command $@ on $i: $result"
+	fi
     done
 }
 
