portbuild: remove hardcoded /var/portbuild.
- Don't hardcode /var/portbuild.
- Upload per-build scripts/ and sources/ directories.
- Scripts which aren't tied to a specific build are uploaded first.

This change makes it effectively possible to checkout portbuild
anywhere and test changes without affecting any other builds.

diff --git a/scripts/dosetupnode b/scripts/dosetupnode
--- a/scripts/dosetupnode
+++ b/scripts/dosetupnode
@@ -15,21 +15,23 @@
 # scripts/ and ${arch}/ directories (e.g. after client reboot)
 
 # configurable variables
-pb=/var/portbuild
+pbc=${PORTBUILD_CHECKOUT:-/var/portbuild}
+pbd=${PORTBUILD_DATA:-/var/portbuild}
+
 arch=$1
 branch=$2
 buildid=$3
 nodelist=$4
 shift 4
 
-. ${pb}/conf/server.conf
-if [ -f ${pb}/${arch}/portbuild.conf ]; then
-    . ${pb}/${arch}/portbuild.conf
+. ${pbc}/conf/server.conf
+if [ -f ${pbd}/${arch}/portbuild.conf ]; then
+    . ${pbd}/${arch}/portbuild.conf
 else
     echo "Invalid arch ${arch}"
     exit 1
 fi
-. ${pb}/scripts/buildenv
+. ${pbc}/scripts/buildenv
 
 # Check for non-fatal rsync errors
 checkerror() {
@@ -55,45 +57,45 @@ setup() {
 
     echo "setting up of $node started at $(date)"
 
-    . ${pb}/${arch}/portbuild.conf
-    . ${pb}/${arch}/portbuild.${node}
+    . ${pbd}/${arch}/portbuild.conf
+    . ${pbd}/${arch}/portbuild.${node}
 
-    ${scp_cmd} -q -p ${pb}/scripts/setupnode ${client_user}@${node}:/tmp || return 1
+    cmdpath=$(cat ${pbc}/scripts/setupnode | ssh -a ${client_user}@${node} 't=$(mktemp -t setupnode); cat >$t; echo $t; chmod 755 $t')
+    case ${cmdpath} in /tmp/*) ;; *) echo "Failed to scp claim-chroot to ${host}."; return 1;; esac
 
-    client_setup="${ssh_cmd} -n ${client_user}@${node} sh /tmp/setupnode ${pb} ${arch} ${branch} ${buildid} ${scratchdir} \"${portsmd5}\" \"${srcmd5}\" \"${bindistmd5}\""
+    client_setup="${ssh_cmd} -n ${client_user}@${node} ${cmdpath} ${pbd} ${arch} ${branch} ${buildid} ${scratchdir} \"${portsmd5}\" \"${srcmd5}\" \"${bindistmd5}\""
     args="${nocopy} ${force}"
 
     ${client_setup} pre-copy ${args} || (echo "pre-copy for ${node} failed"; return 1)
 
     if [ "${norsync}" -eq 0 ]; then
-
-	rsync ${rsync_gzip} -e "${ssh_cmd}" -r -l -p --delete ${pb}/scripts ${pb}/sources \
-	    ${client_user}@${node}:${pb}/
-	checkerror $? || (echo "Copying scripts to ${node} failed"; return 1)
-
 	# client.conf and common.conf can be symlinks outside this dir, so
 	# copy the actual files
-	rsync ${rsync_gzip} -e "${ssh_cmd}" -r -L -p --delete ${pb}/${arch}/*.conf \
-	    ${client_user}@${node}:${pb}/${arch}
+	rsync ${rsync_gzip} -e "${ssh_cmd}" -r -L -p --delete ${pbd}/${arch}/*.conf \
+	    ${client_user}@${node}:${pbd}/${arch}
 	checkerror $? || (echo "copying *.conf to ${node} failed"; return 1)
 
 	# portbuild.* can be symlinks outside this dir, so copy the actual
 	# files
-	rsync ${rsync_gzip} -e "${ssh_cmd}" -r -L -p --delete ${pb}/${arch}/portbuild* \
-	    ${client_user}@${node}:${pb}/${arch}
+	rsync ${rsync_gzip} -e "${ssh_cmd}" -r -L -p --delete ${pbd}/${arch}/portbuild* \
+	    ${client_user}@${node}:${pbd}/${arch}
 	checkerror $? || (echo "copying portbuild* files to ${node} failed"; return 1)
 
-	if [ -f "${pb}/${arch}/clients/bindist-${node}.tar" ]; then
+	if [ -f "${pbd}/${arch}/clients/bindist-${node}.tar" ]; then
 	    rsync ${rsync_gzip} -e "${ssh_cmd}" -r -L -p --delete \
-		${pb}/${arch}/clients/bindist-${node}.tar \
-		${client_user}@${node}:${pb}/${arch}/clients/
+		${pbd}/${arch}/clients/bindist-${node}.tar \
+		${client_user}@${node}:${pbd}/${arch}/clients/
 	    checkerror $? || (echo "Copying bindist-${node}.tar to ${node} failed"; return 1)
 	else
-	    echo "Host customization file not found: ${pb}/${arch}/clients/bindist-${node}.tar"
+	    echo "Host customization file not found: ${pbd}/${arch}/clients/bindist-${node}.tar"
 	    return 1
 	fi
 
 	if [ "${buildid}" != "-" ]; then
+	    rsync ${rsync_gzip} -e "${ssh_cmd}" -r -l -p --delete ${pbc}/scripts ${pbc}/sources \
+		${client_user}@${node}:${builddir}/
+	    checkerror $? || (echo "Copying scripts to ${node} failed"; return 1)
+
 	    rsync ${rsync_gzip} -e "${ssh_cmd}" -r -L -p \
 		${builddir}/ports-${buildid}.tbz \
 		${builddir}/ports-${buildid}.tbz.md5 \
@@ -109,20 +111,20 @@ setup() {
     ${client_setup} post-copy ${args} || (echo "post-copy for ${node} failed"; return 1)
 
     if [ "${queue}" -eq 1 ]; then
-	jobs=$(python /var/portbuild/qmanager/qclient jobs | grep "${node}" | grep "${arch}/${branch}/${buildid} package" | awk '{print $1}' | tail +1)
+	jobs=$(python ${pbc}/qmanager/qclient jobs | grep "${node}" | grep "${arch}/${branch}/${buildid} package" | awk '{print $1}' | tail +1)
 	for j in ${jobs}; do
-	    python /var/portbuild/qmanager/qclient release $j
+	    python ${pbc}/qmanager/qclient release $j
 	done
     fi
 
     if [ "${full}" -eq 1 ]; then
-	${ssh_cmd} ${client_user}@${node} ${sudo_cmd} rm -rf ${pb}/${arch}/${branch}/builds/${buildid}/.ready ${pb}/${arch}/${branch}/builds/${buildid} /tmp/.setup-${buildid}
+	${ssh_cmd} ${client_user}@${node} ${sudo_cmd} rm -rf ${pbd}/${arch}/${branch}/builds/${buildid}/.ready ${pbd}/${arch}/${branch}/builds/${buildid} /tmp/.setup-${buildid}
     fi
 
     echo "setting up of $node ended at $(date)"
 }
 
-pbab=${pb}/${arch}/${branch}
+pbab=${pbd}/${arch}/${branch}
 
 norsync=0
 queue=0
@@ -149,7 +151,7 @@ done
 
 if [ "${norsync}" -eq 0 ]; then
     if [ "${branch}" != "-" -a "${buildid}" != "-" ]; then
-	buildid=$(resolve ${pb} ${arch} ${branch} ${buildid})
+	buildid=$(resolve ${pbd} ${arch} ${branch} ${buildid})
 
 	if [ -z "${buildid}" ]; then
 	    echo "Invalid build ID ${buildid}"
@@ -182,7 +184,7 @@ if [ "${norsync}" -eq 0 ]; then
 fi
 
 if [ "${nodelist}" = "all" ]; then
-    nodelist=$(cat ${pb}/${arch}/mlist)
+    nodelist=$(cat ${pbd}/${arch}/mlist)
 fi
 
 for node in ${nodelist}; do
diff --git a/scripts/pdispatch b/scripts/pdispatch
--- a/scripts/pdispatch
+++ b/scripts/pdispatch
@@ -6,7 +6,8 @@
 #
 # server-side script to dispatch the job to a host via the ptimeout script.
 
-pb=/var/portbuild
+pbc=${PORTBUILD_CHECKOUT:-/var/portbuild}
+pbd=${PORTBUILD_DATA:-/var/portbuild}
 
 arch=$1
 branch=$2
@@ -15,25 +16,25 @@ host=$4
 command=$5
 shift 5
 
-pbab=${pb}/${arch}/${branch}
+pbab=${pbd}/${arch}/${branch}
 
-. ${pb}/conf/server.conf
-. ${pb}/conf/common.conf
-. ${pb}/${arch}/portbuild.conf
-. ${pb}/scripts/buildenv
+. ${pbc}/conf/server.conf
+. ${pbc}/conf/common.conf
+. ${pbd}/${arch}/portbuild.conf
+. ${pbc}/scripts/buildenv
 
 timeout=${PDISPATCH_TIMEOUT}
 loglength=${PDISPATCH_LOGLENGTH}
 hdrlength=${PDISPATCH_HDRLENGTH}
 
-buildid=$(resolve ${pb} ${arch} ${branch} ${buildid})
+buildid=$(resolve ${pbd} ${arch} ${branch} ${buildid})
 if [ -z "${buildid}" ]; then
     echo "Invalid build ID ${buildid}"
     exit 1
 fi
 
 builddir=${pbab}/builds/${buildid}
-buildenv ${pb} ${arch} ${branch} ${builddir}
+buildenv ${pbd} ${arch} ${branch} ${builddir}
 
 # XXX needed still?
 unset DISPLAY
@@ -77,16 +78,22 @@ if [ "x$TRYBROKEN" != "x" ]; then
 fi
 
 chroot=
-. ${pb}/${arch}/portbuild.conf
-test -f ${pb}/${arch}/portbuild.${host} && . ${pb}/${arch}/portbuild.${host}
-chrootdata=$(${ssh_cmd} -a -n ${client_user}@${host} ${sudo_cmd} ${pb}/scripts/claim-chroot ${arch} ${branch} ${buildid} ${pkgname} 2>&1)
+. ${pbd}/${arch}/portbuild.conf
+test -f ${pbd}/${arch}/portbuild.${host} && . ${pbd}/${arch}/portbuild.${host}
+
+# Upload scripts/claim-chroot as per-build scripts aren't in place yet.
+cmdpath=$(cat ${pbc}/scripts/claim-chroot | ssh -a ${client_user}@${host} 't=$(mktemp -t claim-chroot); cat >$t; echo $t; chmod 755 $t')
+case ${cmdpath} in /tmp/*) ;; *) echo "Failed to scp claim-chroot to ${host}."; exit 254;; esac
+chrootdata=$(${ssh_cmd} -a -n ${client_user}@${host} ${sudo_cmd} ${cmdpath} ${arch} ${branch} ${buildid} ${pkgname} 2>&1)
+${ssh_cmd} -a ${client_user}@${host} "rm -f ${cmdpath}"
+
 if [ -z "${chrootdata}" ]; then
     echo "Failed to claim chroot on ${host}"
     exit 254
 fi
 
 case "${chrootdata}" in
-    */var/portbuild/scripts/claim-chroot*)
+    *${cmdpath}*)
 	# Error executing script, assume system is booting
 	chrootdata="wait boot"
 	;;
@@ -111,7 +118,7 @@ if [ $# -ge 2 ]; then
 	    # Make sure to close stdin/stderr in the child
 	    # or make will hang until the child process
 	    # exits
-	    ${pb}/scripts/dosetupnode ${arch} ${branch} ${buildid} ${host} > /tmp/setupnode.$$ 2>&1 &
+	    ${pbc}/scripts/dosetupnode ${arch} ${branch} ${buildid} ${host} > /tmp/setupnode.$$ 2>&1 &
 	    exit 253
 	    ;;
 	error)
@@ -128,8 +135,8 @@ if [ -z "${chroot}" ]; then
     exit 254
 fi
 
-. ${pb}/${arch}/portbuild.conf
-test -f ${pb}/${arch}/portbuild.${host} && . ${pb}/${arch}/portbuild.${host}
+. ${pbd}/${arch}/portbuild.conf
+test -f ${pbd}/${arch}/portbuild.${host} && . ${pbd}/${arch}/portbuild.${host}
     
 rm -f ${builddir}/logs/${pkgname}.log ${builddir}/logs/${pkgname}.log.bz2
 rm -f ${builddir}/errors/${pkgname}.log ${builddir}/errors/${pkgname}.log.bz2
@@ -162,7 +169,7 @@ if [ "${error}" = 0 ]; then
 	# Force rebuild of html page to remove this package from list
 	touch ${builddir}/errors/.force
     fi
-    lockf -k ${pbab}/failure.lock ${pb}/scripts/buildsuccess ${arch} ${branch} ${buildid} ${pkgname}
+    lockf -k ${pbab}/failure.lock ${pbc}/scripts/buildsuccess ${arch} ${branch} ${buildid} ${pkgname}
     log=${builddir}/logs/$pkgname.log
     if grep -q "even though it is marked BROKEN" ${log}; then
 	echo | mail -s "${pkgname} BROKEN but built on ${arch} ${branch}" ${mailto}
@@ -188,11 +195,11 @@ else
 		(echo "Excerpt from the build log at"; echo; echo "  http://${MASTER_URL}/errorlogs/${arch}-errorlogs/${baselogdir}/$(basename $log)";echo;sed -e '/^build started/,$d' $log;echo;echo "  [... lines trimmed ...]";echo;tail -${loglength} ${log}) | mail -s "${pkgname} failed on ${arch} ${branch}" ${mailto}
 	    fi
 	fi
-	lockf -k ${pbab}/failure.lock ${pb}/scripts/buildfailure ${arch} ${branch} ${buildid} ${pkgname}
+	lockf -k ${pbab}/failure.lock ${pbc}/scripts/buildfailure ${arch} ${branch} ${buildid} ${pkgname}
     fi
 fi
 
-${ssh_cmd} -a -n ${client_user}@${host} ${sudo_cmd} ${pb}/scripts/clean-chroot ${arch} ${branch} ${buildid} ${chroot} ${clean}
+${ssh_cmd} -a -n ${client_user}@${host} ${sudo_cmd} ${builddir}/scripts/clean-chroot ${arch} ${branch} ${buildid} ${chroot} ${clean}
 
   # XXX Set a dirty variable earlier and check here
 if grep -q "^build of .*ended at" ${builddir}/logs/${pkgname}.log; then
