portbuild: rsync per-build scripts into /tmp.
We don't always have ${builddir}, so use /tmp/${buildid} instead.

diff --git a/scripts/dosetupnode b/scripts/dosetupnode
--- a/scripts/dosetupnode
+++ b/scripts/dosetupnode
@@ -60,6 +60,12 @@ setup() {
     . ${pbd}/${arch}/portbuild.conf
     . ${pbd}/${arch}/portbuild.${node}
 
+    if [ "${buildid}" != "-" ]; then
+	rsync ${rsync_gzip} -e "${ssh_cmd}" -r -l -p --delete ${pbc}/scripts ${pbc}/sources \
+	    ${client_user}@${node}:/tmp/${buildid}/
+	checkerror $? || (echo "Copying scripts to ${node} failed"; return 1)
+    fi
+
     cmdpath=$(cat ${pbc}/scripts/setupnode | ssh -a ${client_user}@${node} 't=$(mktemp -t setupnode); cat >$t; echo $t; chmod 755 $t')
     case ${cmdpath} in /tmp/*) ;; *) echo "Failed to scp claim-chroot to ${host}."; return 1;; esac
 
